# mdbook build .

[book]
authors = ["aatroxfly"]
language = "zh-CN"
src = "src"
title = "schierke"

[output.html]
# git-repository-url = "https://"
# edit-url-template = "https://"

[output.html.playground]
editable = true
copy-js = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.fold]
enable = true
level = 0